#!"C:\Users\Mohon\AppData\Local\Programs\Python\Python37-32\python.exe"

print("Content-type:text/html\r\n\r\n")

print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<link rel='stylesheet' type='text/css' href='./../css/style.css'>")
print("<link rel='stylesheet' href='./../css/maintain.css' type='text/css'>")
print("</head>")

print("<body>")


main = open("maintainData.txt","r")
mainValue = main.readlines()


print("<div class='fullContainer'>")
print("<!--header-->")
print("<div class='header'>")
print("<h1>"+mainValue[0]+"</h1>")
print("</div>")

print("<!--menu-->")
print("<div class='nav'>")
print("<ul>")
print("<li><a href='./../Home/home.py'>Home</a></li>")
print("<li><a href='./../Site/site.py'>Site Map</a></li>")
print("<li><a href='./../Search/search.py'>Catalogue Search</a></li>")
print("<li><a href='./../Result/result.py'>Result</a></li>")
print("<li><a href='./../Maintain/maintain.py'>Maintenance</a></li>")
print("</ul>")
print("</div>")

print("<!-- Main Content Section -->")
print("<div class='mainContent'>")
print("<div class='wrapContent'>")
print("<div class='spacer'>")

print("</div>")
print("<div class='maintainHeader'>")
print("<p>"+mainValue[1]+"</p>")
print("</div>")
print("<div class='spacer'>")

print("</div>")
print("<div class='dataAddSection'>")
print("<form action='insertmaintain-copy.py' method='post' enctype='multipart/form-data'>")
print("<table class='center'>")
print("<tr>")
print("<td>Categories</td>")
print("<td><input type='text' name='categories'/></td>")
print("</tr>")
print("<tr>")
print("<td>ISBN</td>")
print("<td><input type='text' name='isbn'/></td>")
print("</tr>")
print("<tr>")
print("<td>Title</td>")
print("<td><input type='text' name='title'/></td>")
print("</tr>")
print("<tr>")
print("<td>Author</td>")
print("<td><input type='text' name='author'/></td>")
print("</tr>")
print("<tr>")
print("<td>Publisher</td>")
print("<td><input type='text' name='publisher'></td>")
print("</tr>")
print("<tr>")
print("<td>Price</td>")
print("<td><input type='text' name='price'></td>")
print("</tr>")
print("<tr>")
print("<td>Quantity</td>")
print("<td><input type='text' name='quantity'></td>")
print("</tr>")
print("<tr>")
print("<td>Image</td>")
print("<td><input type='file' name='filename' value='Browse'></td>")
print("</tr>")
print("<tr>")
print("<td></td>")
print("<td><button type='submit'>ADD</button></td>")
print("</tr>")
print("</table>")
print("</form>")
print("</div>")
print("</div>")
print("</div>")


print("<!--footer-->")
print("<div class='footer'>")
print("<p>"+mainValue[2]+" <b>"+mainValue[3]+"</b>.</p>")
print("</div>")

print("</div>")
print("</body>")
print("</html>")
